name: s_frontend
description: Bund Prototyp - Frontend

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 0.0.1+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  shared_preferences: ^0.5.0
  splashscreen: ^1.2.0
  pointycastle: ^1.0.0-rc4
  asn1lib: ^0.5.3
  test: ^1.5.1
  flutter_secure_storage: ^3.1.3
  local_auth: ^0.4.0
  flutter_facebook_login: ^1.2.0
  linkedin_login: ^0.1.1
  #google_sign_in: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/symbols/symbol_email.png
    - assets/symbols/symbol_handysignature.png
    - assets/symbols/symbol_oauth.png
    - assets/symbols/symbol_sms.png

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
